### ISSUE TITLE
[enhance] Utils.badPackageName()

### ISSUE THREAD

**Issue by varhub** [shooash/XHFW3#11]
Hello @shooash,

First of all good job.
I revised last changes a little bit and saw several and inconsistent null and type checking.

I suggest you to standarize complex enough just for stability and correctness.

**I**
```
if Utils.badPackageName(args[0]) return
// it will check nullity and empty name
```

PS: if you wish, use other name/class, like Checker, just to isolate this kind of code (there will be more!)

**Comment by varhub** [comment]
Second suggestion is harder because I dont know which type return api.

Therefore I just show the typo:
```
// int tasksNum = mTasksList.get(packageName)-1;
	Integer tasksNum = mTasksList.get(packageName)-1;
	if(tasksNum == null) tasksNum=0;
					if(tasksNum<1){
```
If `get()` returns null, you already doing a `-1`, so exception is not controlled.

**Comment by varhub** [comment]
**II**
```
if(param==null || param.args==null || param.args.length<MainXposed.mCompatibility.TaskRecord_Intent+1 || ...
// condense these generic checking in.something like:
Checher.argAvailavility(params, index)
```

**Comment by shooash** [comment]
Got "fail-safe" getters. As for the "typo" - changed these parts of code already, revising SystemHooks currently, I'll update the git as soon as it's ready. Thank you for your feedback and help!
